### ISSUE TITLE
`build_sdk` fails

### ISSUE THREAD

**Issue by schmidtw** [pulumiverse/pulumi-vra#5]
The `build_sdk` fails due to a check to see if the workspace is clean.  Should I remove the generated files?

https://github.com/pulumiverse/pulumi-vra/actions/runs/3207733673/jobs/5242953795#step:17:1

**Comment by schmidtw** [comment]
@ringods do you have any suggestions for how to fix this?

**Comment by ringods** [comment]
@schmidtw the build setup generates the SDKs and warns if there are changes to what is committed to Git. If you build locally on your machine, do you have changed SDK files? If so, commit these to git. If not, please check if you are using the same Go version as used on Github Actions.

**Comment by schmidtw** [comment]
Thank you for the suggestions @ringods the go version was it.
